// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MagicQuizDesktop.Models;
//
//    var loginUser = LoginUser.FromJson(jsonString);

namespace MagicQuizDesktop.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LoginUser
    {
        [JsonProperty("token")]
        public string Token { get; set; }

        [JsonProperty("user_id")]
        public int UserId { get; set; }
    }

    public partial class LoginUser
    {
        public static LoginUser FromJson(string json) => JsonConvert.DeserializeObject<LoginUser>(json, MagicQuizDesktop.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this LoginUser self) => JsonConvert.SerializeObject(self, MagicQuizDesktop.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
