// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MagicQuizDesktop.Models;
//
//    var rank = Rank.FromJson(jsonString);

namespace MagicQuizDesktop.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Rank
    {
        public int RankNumber { get; set; }
        public string RankColor { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("user_id")]
        public int UserId { get; set; }

        [JsonProperty("score")]
        public int Score { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }
    }

    public partial class Rank
    {
        public static Rank FromJson(string json) => JsonConvert.DeserializeObject<Rank>(json, MagicQuizDesktop.Models.Converter.Settings);
    }
}
